config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary create-btn' %>
<% end %>

app/views/articles/edit.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'Wikinimous', articles_url, { class: "navbar-brand"} %>
  <%= link_to 'New Article', new_article_url, { class: "nav-link"} %>
</nav>

<div class='container form-container'>
  <h1>Editing Article</h1>
  <%= render 'form', article: @article %>
</div>

<%= link_to articles_url(@article) do %>
  <i class="fas fa-undo" id="back-link">Back</i>
<% end %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-light bg-light">
  <%= link_to 'Wikinimous', articles_url, { class: "navbar-brand"} %>
  <%= link_to 'New Article', new_article_url, { class: "nav-link"} %>
</nav>

<div class='container index-list'>

  <div class="col-sm-8 col-sm-offset-2">
    <% @articles.each do |article| %>
        <div class="row title-row"><%= link_to "#{article.title}", article_url(article) %></div>
        <div class="row content-row"><%= article.content %></div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'Wikinimous', articles_url, { class: "navbar-brand"} %>
  <p class = "navbar-info">Add a new article</p>
  <%= link_to 'New Article', new_article_url, { class: "nav-link"} %>
</nav>

<div class='container form-container'>
  <%= render 'form', article: @article %>
</div>

<%= link_to articles_url(@article) do %>
  <i class="fas fa-undo" id="back-link">Back</i>
<% end %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-light bg-light">
  <%= link_to 'Wikinimous', articles_url, { class: "navbar-brand"} %>
  <%= link_to 'New Article', new_article_url, { class: "nav-link"} %>
</nav>

<div class="container show-container">
  <div class="row show-title-row">
    <%= @article.title %>
    <%= link_to edit_article_url(@article) do %>
      <i class="fas fa-pencil-alt"></i>
    <% end %>
    <%= link_to article_url(@article), method: :delete,
        data: { confirm: 'Are you sure?' },
        remote: true do %>
        <i class='far fa-trash-alt'></i>
    <% end %>
  </div>

    <div class="row show-image">
    <img src="#{Faker::LoremFlickr.image}" alt="">
  </div>

  <div class="row show-content-row">
    <%= @article.content %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>